import './globals.css'
import Header from './common/components/Header'
import Footer from './common/components/Footer'

export const metadata = {
  title: 'Mercado Libre',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className='flex flex-col justify-between min-h-screen'>
        <div>
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
